---
title: "NASA Disasters: Documentation"
subtitle: "Resources for Disasters Datasets, Stories, and Visualizations"
---

## Welcome {#welcome}

The [NASA Disasters Program](https://appliedsciences.nasa.gov/what-we-do/disasters) advances science and builds tools to help communities make informed decisions for disaster planning. We develop free and accessible resources that use Earth observations to reveal how natural hazards interact with vulnerability, exposure, and coping capacity in a changing climate. 

On this site, you can find the technical documentation for the services used to visualize data, how to connect to these services, how to load datasets, how the datasets were transformed into cloud-optimized formats that enable efficient cloud data access, and how to visualize datasets.


## Contents

1. A guide to access [AWS](aws.qmd) resources, with guidelines to utilize AWS commands and operations.
2. Directions on how to setup [GitHub](git-github-comprehensive-guide.qmd), access a repository, use commands, and understand the GitHub workflow in Disasters. 
3. How to use JupyterHub to work collaboratively on notebooks within a repositroy and the Disasters framework.


## Contact

For technical help or general questions, please contact the support team using the [feedback form](https://docs.google.com/forms/d/e/1FAIpQLSeVWCrnca08Gt_qoWYjTo6gnj1BEGL4NCUC9VEiQnXA02gzVQ/viewform).